### ISSUE TITLE
Add labels, milestones, Wiki from the second project 

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartParking#10]
A little issue I will do for making such small, obvious additions: 

- [x]  Add  labels

- [x]  Add milestones

- [x]  Update wiki from second project

- [x] Update readme.MD 

- [x] check Maven is working

- [x] check travis is working
