### ISSUE TITLE
Weekly Log David Cohen

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/SmartParking#2]
# The Weekly Log
New for semester 2, a fresh new page with a different name.
This is meant to help in monitoring everyone's assignments in the projects and what they are currently involved with. 

Please use this as a weekly log from week 2 till the end of semester, both for you and me to see.
Log here *_past_* work that is finished, as well as *_current_* tasks you are doing.

Whenever possible, please include an issue number that you are working on, or that you have finished working on.
Best to use the bulleted list as a way to put things organized. 

**Have a great semester!**

**Comment by DavidCohen55** [comment]
## weekly update (20-23.3) :
- [x] Upload the server to the git
- [x] Population of db for the project
- [x] Starting to organize to Logic files and delete unnecessary

**Comment by TomPalny** [comment]
well done for the first week.
whenever possible in the coming weeks, reference next to your bullet points the issue numbers that are relevant to what you're working on. If there is no relevant issue, such as when you're learning a new technology such as ionic, leave it without issue number ref.

**Comment by DavidCohen55** [comment]
## weekly update (24.3-1.4) :
- @Shahar-Y and I started working on installing ionic (#21) in order to create a basic project and start integrating ionic to the project's GUI, according to Yaels instructions in her issue.
- I've also continued the refactoring but didn't commit because I want to be sure that it is ok before uploading it (#17). 

## This week plans:
- [x] @Shahar-Y  and I intend to continue the progress with the ionic integration. (#21)
- [x] Finish the refactoring (#17).
- [x] working on the test and see if we need to get a better coverage

**Comment by TomPalny** [comment]
Hi David,
Please update the log with further work. Don't forget to reference issues you're currently working on

**Comment by DavidCohen55** [comment]
## Weekly Log
I'm sorry about not writing the weekly log for awhile, it won't happen again 😟 
### Back to business...
- @Shahar-Y and I where working on Ionic and how to use it to the project #21, doing so we've learn basic Javascript, Typescript & Html.
- Now we are working on issue #34, we encounter number of problems, but in the end we managed to establish a connection to the server and present data from it to the ionic app, so now we have both client side and server side with a very basic functionality.
- I've made a wiki about the test coverage #29 .
- I've worked on a problem we had with Travis CI, that happened because of Springboot, now everything is fine (there wasn't an issue about it).
- I've fixed problems with duplications in the DB, which caused the problem with the tests #25 .
- Finish the refactoring #17.
- Making the presentation for the meeting #28.

### Plans for the future:

- [x] Mainly continue the work with issue #34, so we can get information from the server and make it work with Ionic app.
- [x] The next steps are to create authentication of the user using @zahimizrahi 's GUI #37 .
- [x] Checking the functionality available for us with the users and dealing with connection errors that could be on the way.

I hope it covers everything 🙏

**Comment by DavidCohen55** [comment]
## Weekly Log
- Fixed the bug presented in issue #38 with Shahar.
- Connected the java code to ionic services, in order to get data from the server, and upload it to the localhost, issue #34.
- Created authentication with Shahar, issue #37.
  -  It works, the issue is still open because we still have a problem with presenting the data and we are working on it.
- Opened issue #39 for learning the SpringBoot web services.

## Next Week:
- [x]  Finish with the Login & Register page, issue #37.
- [x] When we will be sure that we understand everything I will start to work on the web services for parking areas and parking spots, relevant issues will be attach to the weekly log as soon as I start to working on it.

**Comment by DavidCohen55** [comment]
## Weekly Log
- Continue learning Spring Boot services and implemented services, issue #39 .
- Finish with the Login page, issue #37, the register part will be done by @Shahar-Y .
- I started working on the web services for parking areas, parking spots & locations and also checked that all of them works correct, issue #42 .
- Helped @Shahar-Y with some problems with the services.

## This Week:
- [x] Working on storing paths class, issue #46 .
- [x] Working on writing services for stored paths, issue #44 .
- [x] Continue Working on Location services #42 .
- [x] Continue the Spring Boot services learning , issue #39 .

**Comment by DavidCohen55** [comment]
## Weekly Log
- I've been working on storing paths class and closing it, issue #46 .
- I've been working on writing services for stored paths and closing it, issue #44 .
- Continued Working on Location services and closing it, issue #42 .
- Continued the Spring Boot services learning , issue #39 .

## This Week:
This two weeks are going to be my weeks of so there isn't something to write.
All of my issues for this sprint are closed and if anyone need me help I'm here to help 😄

**Comment by DavidCohen55** [comment]
## Weekly Log
- Got back from weeks off.
- Caught up with the team status.
- Tried to upload the SpringBoot application to Heroku.
- Database cleaning.

## This Week:
- [x] Working on the poster.
- [x] Working on moving the SpringBoot files to work with Heroku, (thanks to @shaysegal for uploading the server to Heroku 👏👏👏)
- [x] Working on saved last paths for user.

**All of the above will be connected to issues after I will open them.**

**Comment by DavidCohen55** [comment]
# Last Weekly log
first of all, I would like to apologize about the missing weekly logs, all of them will be explained here:

## 2 Weeks ago
- Making a poster for the project #69 
- Worked on uploading spring boot to heroku #65 
- Worked last searches, java function and services #68 
- Maintaining the services
- Working on refactoring code #74 
- Working on Improving test coverage #73 

## Previous Week
- Working on refactoring code #74 
- Working on Improving test coverage #73 
- Worked on retrieving last parking of user #76 ,also worked on bug relevant to it #85 
- Made an google doc for our team members, which included a description of the bugs we had to work on #105.

## Last Week of the Semester
In this weekend @Shahar-Y & myself had a two white nights in a row and almost a third 🌕, at the second @shaysegal joined the fun.
- Encounter with a service request problems #91 
- Added identification for each user, so that more than one user would be able to log in, and send service requests. #92.
- Worked on car evacuation services and alerts #108 
- Update the navigation functionality to work faster and also its services #109 
- Add popup support in the project, which means what can you do in the popups #117 
- solve small bugs that referenced in #105 
- Working on refactoring code and delete unnecessary #74 
- Write the user manual #122 
- worked with @Shahar-Y on bug in reality test #149 
- helped solving problems in reality problems
- checked app functionality in web & android.
- Also few contributions to @Shahar-Y commits and problem solutions in the white nights, and he helped me also in my work 😘

In the end, like all good things come to an end...
It was a challenging year, and this semester was more intense then the first but we worked it through.
thank you for all the good time and support @zahimizrahi @Shahar-Y @sefialbo @Shahar-Y ❤️ 

![gif](https://media.giphy.com/media/12xSrwKxHxB3BS/giphy.gif)
