### ISSUE TITLE
Weekly Log for Shay Segal

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/SmartParking#5]
# The Weekly Log
New for semester 2, a fresh new page with a different name.
This is meant to help in monitoring everyone's assignments in the projects and what they are currently involved with. 

Please use this as a weekly log from week 2 till the end of semester, both for you and me to see.
Log here *_past_* work that is finished, as well as *_current_* tasks you are doing.

Whenever possible, please include an issue number that you are working on, or that you have finished working on.
Best to use the bulleted list as a way to put things organized. 

**Have a great semester!**

**Comment by shaysegal** [comment]
this week (20-23.3) I :
- [x] created new server and db for the project #7 
- [x] tested connection to the server #9
- [x] migrate issues,wikis and backlog from the Smart Parking Management project (probably related to #10)
- [x] designed new logo for the project
- [x] start reorganizing the map classes   #15

**Comment by TomPalny** [comment]
Hi Shay, please reference issue numbers to all the things you did that relate to them

**Comment by shaysegal** [comment]
summery of past weeks work 
week log of 24.3-1.4 - week off
week log 2-8.4 learn ionic basics and add an template map #24 
week log 9-15.4 passover
week log 16-22.4 exploring new features of map in ionic #31

**Comment by yossigil** [comment]
> week log 16-22.4 exploring new features of map in ionic #31
Not much of a contribution I think

**Comment by shaysegal** [comment]
weekly log :

- [x] worked on presentation #28 
- [x] worked with @sefialbo on extending map features #31 
- [x] helped @DavidCohen55 and @Shahar-Y with integrate java to ionic #34 
- [x] moved  map to ionic demo with @sefialbo #32

**Comment by shaysegal** [comment]
weekly log 30.4-6.5:
- [x] added current location recognition to the map and styled the icon #36 
- [x] added choosing source and destination page to the ionic project #35 worked with @sefialbo

**Comment by shaysegal** [comment]
weekly log 7.5-13.5:
- [x] finalize work on map direction panel #35 
- [x] add record route option #40
- [x] looked for alternatives for displaying user generated routes (will elaborate when implement) #45

**Comment by shaysegal** [comment]
weekly log 14.5-20.5:
- [x] helped solve problem with login service #34 
- [x] help to write location service for ionic #42 
- [x] connect the location service to ionic and show the points of interest in gui(+ current location option) #45
- [x] connect the parking area service to ionic and show them on map #45 
- [x] solve problem of SringBoot services didn't work on some browsers (not really have an issue , @DavidCohen55 can you open one that explain it?)

**Comment by shaysegal** [comment]
weekly log 21.5-27.5+28.5-5.6:
in the past two weeks i worked on :
- [x] continue to implement to record route and to navigate to the best parking area#47
- [x] help shahar solve bug in login #43  
- [x] helped zahi to solve bug in register #49 
and for the next two days i'll start working on the simulation #53 of driving/walking of a path (since from tuesday im on a week off)
- [x] patched two routes (walking/driving) #55

**Comment by shaysegal** [comment]
weekly log :
6.6-13.6 - week off
14.6 -17.6:
 - [x] finish the issue of simulate driving/ walking #53 
 - [x] fix bug of zoom after draw route #63

**Comment by shaysegal** [comment]
weekly log 18.6-25.6:
 - [x] upload spring boot to heroku #65 
 - [x] worked on poster #69 
 - [x] create log system for ionic app #75 
 - [x] test ionic app on android device #86 
 - [x] removed marker of routes #83 
 - [x] investigate bug #71

**Comment by yossigil** [comment]
:+1:

**Comment by shaysegal** [comment]
weekly log 26.6-end of all time:
- [x] make current location marker follow mouse #89 
- [x] create identity per device #90 
- [x]  fix CORS problem and update errors #91 #94 
- [x]  fix laggy voice #98 
- [x] add key to ts services #92
- [x] worked on last searches #102
- [x] disable back button #106 
- [x] worked on check simulation #110
- [x] navigation work more then one time after simulation #111 
- [x] work on #105 **a lot of** little bugs for more details please check commits related to this issue
- [x] worked on getting app to work on android device #86 
- [x] fix android bug - toughest bug ever!!!! #118 
- [x] fix show recorded route again #121 
- [x] worked with @zahimizrahi  on #114 
- [x] tested Info Evaluation (my wiki about it : https://github.com/TechnionYP5777/Info-Evaluation/wiki/experience-in-installation-of-Shay-Segal) , also on reality game i worked on (#146 #142 #141 #140 #136 #134 #123)
- [x] tomorrow : participate in presentation of the project in the project fair

## one last thing ...
- [x] Done write weekly log!
It was a great honor to work with you guys , good luck to us all 👍 
@TomPalny @sefialbo @DavidCohen55 @Shahar-Y @zahimizrahi

**Comment by yossigil** [comment]
My remote impression is that you personally made a great progress this semester

**Comment by shaysegal** [comment]
Thank you Yossi ,I really glad to hear that
